version: '3.8'

services:
  # FastAPI Application
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - money_saver_network

  # Redis for caching (optional, for future enhancements)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - money_saver_network

  # PostgreSQL for local development (optional - use if not using Supabase for local dev)
  # Uncomment if you want local database instead of always connecting to Supabase
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: money_saver
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - money_saver_network

volumes:
  redis_data:
  # postgres_data:  # Uncomment if using local PostgreSQL

networks:
  money_saver_network:
    driver: bridge