"""make_week_index_nullable_with_updated_constraints

Revision ID: 1657535cc443
Revises: ba739c151d87
Create Date: 2025-08-06 23:08:43.986769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1657535cc443'
down_revision: Union[str, None] = 'ba739c151d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the old constraint that doesn't allow null week_index
    op.drop_constraint('ck_weekly_amount_week_index_positive', 'weekly_amounts', type_='check')
    
    # Create new constraint that allows null week_index  
    op.create_check_constraint(
        'ck_weekly_amount_week_index_positive',
        'weekly_amounts', 
        'week_index IS NULL OR week_index > 0'
    )
    
    # Drop and recreate the unique index with proper null handling
    op.drop_index('idx_weekly_amounts_plan_week_unique', table_name='weekly_amounts')
    op.create_index(
        'idx_weekly_amounts_plan_week_unique',
        'weekly_amounts',
        ['saving_plan_id', 'week_index'],
        unique=True,
        postgresql_where=sa.text('week_index IS NOT NULL')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert the unique index back to original
    op.drop_index('idx_weekly_amounts_plan_week_unique', table_name='weekly_amounts')
    op.create_index(
        'idx_weekly_amounts_plan_week_unique',
        'weekly_amounts',
        ['saving_plan_id', 'week_index'],
        unique=True
    )
    
    # Revert the check constraint back to original
    op.drop_constraint('ck_weekly_amount_week_index_positive', 'weekly_amounts', type_='check')
    op.create_check_constraint(
        'ck_weekly_amount_week_index_positive',
        'weekly_amounts', 
        'week_index > 0'
    )
    
    # ### end Alembic commands ###
