"""add_email_notifications_to_users

Revision ID: 2025080701
Revises: 1657535cc443
Create Date: 2025-08-07 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2025080701'
down_revision: Union[str, None] = '1657535cc443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add email notification preferences to users table
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('last_reminder_sent', sa.DateTime(timezone=True), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove email notification preferences from users table
    op.drop_column('users', 'last_reminder_sent')
    op.drop_column('users', 'email_notifications')
    
    # ### end Alembic commands ###